### ISSUE TITLE
Segfault on Gio::VolumeMonitor when gtk3 is required.

### ISSUE THREAD

**Issue by dark-yux** [ruby-gnome2/ruby-gnome2#301]
When writing an app with gtk3 that required `Gio::VolumeMonitor` the app crashed with a segfault. Using IRB i figured out that gtk3 and `Gio::VolumeMonitor` can't work together in certain circumstances. Type this in IRB.
```
irb>require "gtk3"
irb>require "gio2"
irb>v = Gio::VolumeMonitor.get
# CRASH -> segfault
```

**Comment by kou** [comment]
Thanks for your report.
It seems that it has been fixed at master.

**Comment by dark-yux** [comment]
It's still a problem in ruby-gio 2.2.5 this time when calling mounts

```
irb>require "gtk3"
irb>require "gio2"
irb>v = Gio::VolumeMonitor.get()
irb>v.mounts
# CRASH -> segfault
```

**Comment by kou** [comment]
gio gem 3.0.0 will fix it.
