### ISSUE TITLE
define_deprecated_method_by_hash_args recursive stack to deep

### ISSUE THREAD

**Issue by eumario** [ruby-gnome2/ruby-gnome2#381]
I have run into an issue when attempting to develop my App and library around Gtk3 (GI Interface), where when attempting to create a MessageDialog, it fails to run, with an Stack Level To deep exception, when executing new on Gtk::MessageDialog.

A Minimal Example that Reproduces the exception:

```ruby
require 'gtk3'

win = Gtk::Window.new
win.title = "Test Recursion Bug"
win.signal_connect("destroy") { Gtk.main_quit }

btn = Gtk::Button.new(:label => "Run Message Dialog")
btn.signal_connect("clicked") do
        dialog = Gtk::MessageDialog.new(
                :parent => win,
                :flags => [:modal,:destroy_with_parent],
                :type => :question,
                :buttons_type => :none,
                :message => "This is a test message to see if we get an exception.")

        dialog.add_button("_Cancel",Gtk::ResponseType::CANCEL)
        dialog.add_button("_No",Gtk::ResponseType::NO)
        dialog.add_button("_Yes",Gtk::ResponseType::YES)

        dialog.title = "Test Recursion bug"
        dlgRet = dialog.run
        if dlgRet == Gtk::ResponseType::YES
                puts "1"
        elsif dlgRet == Gtk::ResponseType::NO
                puts "0"
        else dlgRet == Gtk::ResponseType::CANCEL
                puts "-1"
        end
        dialog.destroy
end

win.add(btn)
win.show_all

Gtk.main
```

This is from Ruby-Gnome2 git repo, GI Interface.

**Comment by eumario** [comment]
Just to note, this occurs in glib2 library.

**Comment by kou** [comment]
Thanks for your report!
I've fixed it.

**Comment by eumario** [comment]
Great work.  Though, just to comment, that you forgot to do the symbol or_all part with the flags, and such, [:modal,:destroy_with_parent] = Gtk::DialogFlags::MODAL && Gtk::DialogFlags::DESTROY_WITH_PARENT

**Comment by kou** [comment]
I'm sorry but I couldn't understand what you say.
Did you say that `[:modal, :destroy_with_parent]` should be evaluated as `Gtk::DialogFlags::MODAL & Gtk::DialogFlags::DESTROY_WITH_PARENT`?

**Comment by eumario** [comment]
Correct.  In the no-gi version of the gtk3 bindings, evaluation of ```[:modal, :destroy_with_parent]``` was evaluated to ```Gtk::DialogFlags::MODAL && Gtk::DialogFlags::DESTROY_WITH_PARENT```  but it doesn't accept this in the GI Version.

**Comment by kou** [comment]
Really? How did you confirm the behavior?

`[:model, :destroy_with_parent]` is evaluated as `Gtk::Dialog::Flags::MODAL | Gtk::Dialog::Flags::DESTROY_WITH_PARENT` in no-gi version.

```ruby
require "gtk3" # no-gi

dialog = Gtk::MessageDialog.new(:flags => [:modal, :destroy_with_parent])
p dialog.modal? # => true
p dialog.destroy_with_parent? # => true

dialog = Gtk::MessageDialog.new(:flags => [:modal])
p dialog.modal? # => true
p dialog.destroy_with_parent? # => false

dialog = Gtk::MessageDialog.new(:flags => [:destroy_with_parent])
p dialog.modal? # => false
p dialog.destroy_with_parent? # => true
```

And is `Gtk::DialogFlags::MODAL && Gtk::DialogFlags::DESTROY_WITH_PARENT` really what you want?

```ruby
require "gtk3" # no-gi
p(Gtk::Dialog::Flags::MODAL && Gtk::Dialog::Flags::DESTROY_WITH_PARENT) # => #<Gtk::Dialog::Flags destroy-with-parent>
```

**Comment by eumario** [comment]
When I substitute the flags parameter with the Gtk::DialogFlags class, it works fine, but when I use the symbols, it throws this error to me:

```
[eumario@ichigo test]$ ruby test_bug.rb 
/home/eumario/.gem/ruby/2.2.0/gems/gtk3-2.2.6/lib/gtk3/loader.rb: line 37
   (null)-WARNING **:Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
/home/eumario/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb: line 293
   GLib-GObject-WARNING **:The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
/home/eumario/.gem/ruby/2.2.0/gems/gtk3-2.2.6/lib/gtk3/message-dialog.rb:42:in `initialize': no implicit conversion of Array into String
	 from /home/eumario/.gem/ruby/2.2.0/gems/gtk3-2.2.6/lib/gtk3/message-dialog.rb:42:in `new'
	 from /home/eumario/.gem/ruby/2.2.0/gems/gtk3-2.2.6/lib/gtk3/message-dialog.rb:42:in `initialize'
	 from /home/eumario/.gem/ruby/2.2.0/gems/glib2-2.2.6/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'
	 from test_bug.rb:9:in `new'
	 from test_bug.rb:9:in `block in <main>'
	 from /home/eumario/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:112:in `call'
	 from /home/eumario/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:112:in `invoke'
	 from /home/eumario/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:112:in `block in define_singleton_method'
	 from test_bug.rb:35:in `<main>'
```
And your right, it was meant to be Gtk::DialogFlags::MODAL | Gtk::DialogFlags::DESTROY_WITH_PARENT

**Comment by kou** [comment]
It seems that your glib2 is old.

**Comment by eumario** [comment]
Just ran a test, Removing the glib2 gem, and re-installing it, and it seems to come up with the same error.  Did an update to the git clone I did, just to make sure before hand, and it says that I'm up to date on the latest revision.

**Comment by kou** [comment]
Please create a new issue and paste the `test_bug.rb`.
